language: node_js
node_js:
- v6
- v5
- v4
addons:
  mariadb: '10.1'
  apt:
    packages:
    - expect
after_success: coveralls
env:
  global:
  - MOCHA_SUITES=all
  - secure: Fdo2JmN3/+xoKnXcvoza/XEdinL71oy/s9QzjOxbg0D8o7/B0TccM0z572r59cWioT2uvVxncT7qig5kOB+6rqbjyQqMXKjG5CJl7Ka1vzHwTo7hxwgMaNCy0HBrA+88qwSRWPmT0RR5tgKVxCIqneyWey/qZSE61VpnmdDXnOhz2LCn7tmvlECAQEixVAfo89bRJUnZaiMh50Wxt4dtK7mxekfSujx0W/j+zM3jxZNer7fbxKED/H6WSiQF0UIGufMtXOtz4dobR/Fbs7cfZ6/Y0mY56nwscnLIEiNhpLI+9bWXZbR+UIfeosUIyKm9NiFy9VnkngMHOGMaN0CVuRU6H75kN4feG2uatKMcsQkawH7qmJjB3eWCiWbT45MiGMXKdRhfxH5vpLoYSN6y1yNw+k7JeBL7m1uSpe2El8hj8gKkqKcl8C980tAvxWf+DyugelEUKGXE2QJDHwnddKN9yGCO18stOtBd0pnMjWmxTm2s7u1kRmAp1VAV8z1a4y+oP97y9zghqV+3Y98yPJj/Zsl1gttheapApcVVgDWCGESTvs3omhITkkrQRGhR7qGOcswBv2MVOW2eZKXxi82KDYOvpL0oyQEy3JAfoWP4VMLHb21bquhAo0SgpjnWaCGRIiOiN2bAsCD17+JjdpVCzGG9ZwYUFOPV6iqaGEo=
  - secure: ZSUtsnh1KvFdkDeD31GMnaA9yjytqAjByZU5NxtmNWWkVibcBX4Jdfzddt15ECM5wQ/SiQFLH+IbYHN2abvLvXou0xiefAlTgjdvC/XEQ5QG5HYwusQ5x+7OwAoWbuQlwYi2bL4XHSWahWu4pznfoTS+RrD6R1mT3Q2Ss36N4rslSqrbvzVFzsXUIpbFVo8OrBOhM4k6nP07Nc+h2DDYyl2w2QTuWlE6fI2tMYoqPRUvd4O+fTA0wu0NY400YPXKA4hjH4nn3+p5A1PyKaT1HQvE7uSkab6OgoEss4iNJ05QMczwAwHGBFJHO4/fuoWC1+1zhMLUoqXYTAuDmqN242aZG+PcjABSvPvC+BvY180yaIUNNAiE+qwSgcjSv/tIY248Zy+KOT7mQqDnzr0fms7K70ylzIFQ5S5UE7djjUX1Kt44/bSp0tPAvDoWJgT1n73JuF+ZAfh7ZJkA8AGFfwqafNebfNfJp++YsRkRz9cRcBRshfIhwveXjuuaBrEEt9Qab80ugJAsA0n5W3TJ3RC7CLkoSy6H6kwCtEbTaXqQWvSrf4NeS4ESZjj/Z+JaLO6u8ZuxlDJPW2jdxHgWCfEBeq2S/lujw6mAp8tTPrVhPY/v0t6Tt3FRFZplO1H0+1+IAusXLTzgEpLjv/rZChrb74gufo3MoRIbW2Vi3ZA=
